name: Release Web Client

on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths:
      - "flutter/version.properties"

jobs:
  build-web:
    runs-on: self-hosted
    defaults:
      run:
        working-directory: flutter

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Obtain solution name for folders/URL from repository name
        run: |
          SOLUTION_NAME=${GITHUB_REPOSITORY#*/}
          echo "Solution name: $SOLUTION_NAME"
          echo "SOLUTION_NAME=$SOLUTION_NAME" >> "$GITHUB_ENV"

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "24"

      - name: Install Yarn Classic v1.22
        run: npm install -g yarn@1.22.22

      - name: Install protoc
        uses: arduino/setup-protoc@v3
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Flutter 3.24.5
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.24.5"

      - name: Build JS
        working-directory: flutter/js
        run: |
          yarn install --frozen-lockfile
          yarn build:release

      - name: Build Flutter Web
        run: |
          flutter pub get
          flutter build web --release

      - name: Archive release directory
        run: |
          tar -czf release.tar.gz ./build/web

      - name: Read version from version.properties
        run: |
          VERSION_NAME=`cat ./version.properties | grep version.name | cut -d'=' -f2 | sed 's/ //g'` 
          echo "Version to be published: $VERSION_NAME"
          echo "VERSION_NAME=$VERSION_NAME" >> "$GITHUB_ENV"

      - name: Publish artifact
        run: |
          mkdir -p "/media/store/release/$SOLUTION_NAME/$VERSION_NAME/"
          cp release.tar.gz /media/store/release/$SOLUTION_NAME/$VERSION_NAME/release.tar.gz
          echo "[$SOLUTION_NAME $VERSION_NAME](http://builder.tmgltd.co.il/$SOLUTION_NAME/$VERSION_NAME)" >> $GITHUB_STEP_SUMMARY

      - name: Add release tag to sources
        run: |
          git config user.name builder
          git config user.email build@tmgltd.co.il
          git tag $VERSION_NAME -a -m "$VERSION_NAME released"
          git push origin $VERSION_NAME
